#!/bin/bash
#Creates the ingest and testing .conf files from the arguments passed.
##Created by Rob Collins robert.collins@ltnglobal.com July 2020

#Define variables
rp=$1
chan_num=$2
overlay=$3
flc=$4
path=~ltn/scripts_current

#Function declarations
function ingest {
         cp $path/ingest.conf.example $path/ingest.conf
         file=$path/ingest.conf
         sed -i "s/RESTART_ON_BOOT=.*/RESTART_ON_BOOT=YES/; s/RECEIVE_PORT=.*/RECEIVE_PORT=$rp/;
                 s/MOON_PORT=.*/MOON_PORT=$overlay/; s/SEND_GROUP=.*/SEND_GROUP=$chan_num/; s/FLOWC_ID=.*/FLOWC_ID=$flc/;
                 s/LOG_FILE=.*/LOG_FILE=ingest.log/" $file
}

function ingest-test {
        cp $path/ingest.conf $path/ingest-test.conf
        file=$path/ingest-test.conf
        sed -i "s/RESTART_ON_BOOT=YES/RESTART_ON_BOOT=NO/; s/RECEIVE_PORT=.*/RECEIVE_PORT=4991/;
                s/SEND_GROUP=.*/SEND_GROUP=$(echo $chan_num | sed s/.0/.99/)/; s/LOG_FILE=.*/LOG_FILE=ingest-test.log/;
                s/$flc/$flc-bw/" $file
}


function recv-test {
        cp $path/recv.conf.example $path/recv-test.conf
        file=$path/recv-test.conf
        sed -i "s/MOON_PORT=.*/MOON_PORT=$overlay/; s/RECEIVE_GROUP=.*/RECEIVE_GROUP=$(echo $chan_num | sed "s/.0/.99/")/;
                s/LOG_FILE=.*/LOG_FILE=recv-test.log/; s/BUF_TIME=.*/BUF_TIME=150/; s/FLOWC_ID=.*/FLOWC_ID=$(echo $flc | sed s/-i/-recv-bw/)/" $file
}

if [[ $# -ne 4 || $1 -eq "--h" ]]
then
        echo "usage: mktest [receive_port] [channel_number] [overlay] [flow_client_id]"

else
        ingest
        ingest-test
        recv-test
	cd $path
	ls

fi
