#!/bin/bash
#This script is meant to automate the majority of the processes in the "Activation/Network/Video Testing" Confluence guide (https://ltnglobal.atlassian.net/wiki/spaces/documentation/pages/93650991/Activation+Network+Testing+Video+Testing)
##Written by:
#Rob Collins rob.collins@ltnglobal.com July 2020

#Info gathering
echo -n "Enter hostname or ip address of appliance: "
read host

echo -n "Will this appliance be part of a redundant pair? (y/N): " 
read response

#Software Deployment
case $response in
	[yY])	#<commented for testing>echo  /usr/local/sbin/deploy_software.sh -f -s -a -c -e -G $host &&;;
		echo -e "Software successfully deployed:\n Flow Client\n Spread\n Schedule Agent\n Equipment Controller\n LTN Encoder\n LTED Decoder";;
		
	[nN])	#<commented for testing>echo  /usr/local/sbin/deploy_software.sh -f -a -c -e -G $host &&;;
		echo -e "Software deployed:\n Flow Client\n Schedule Agent\n Equipment Controller\n LTN Encoder\n LTED Decoder";;	
esac

#DNS and NTP Check
ssh -p 3999 $host nslookup www.google.com 1> /dev/null &&
if [ $? -ne 0 ]
then
        echo DNS Check....Failed

else
        echo DNS Check....Passed
        ntpq -p
fi

#Software Configuration
#Define variables
echo -n "Receive Port: "
read rp
echo -n "Channel Number: "
read chan_num
echo -n "Overlay: "
read overlay
echo -n "Flowclient ID: "
read flc
sc_path=~ltn/scripts_current
mnumber=$((${overlay:0:2}-40))

#Function declarations
function ingest {
         cp $path/ingest.conf.example $path/ingest.conf
         file=$path/ingest.conf
         sed -i "s/RESTART_ON_BOOT=.*/RESTART_ON_BOOT=YES/; s/RECEIVE_PORT=.*/RECEIVE_PORT=$rp/;
                 s/MOON_PORT=.*/MOON_PORT=$overlay/; s/SEND_GROUP=.*/SEND_GROUP=$chan_num/; s/FLOWC_ID=.*/FLOWC_ID=$flc/;
                 s/LOG_FILE=.*/LOG_FILE=ingest.log/" $file
}


function ingest-test {
        cp $path/ingest.conf $path/ingest-test.conf
        file=$path/ingest-test.conf
        sed -i "s/RESTART_ON_BOOT=YES/RESTART_ON_BOOT=NO/; s/RECEIVE_PORT=.*/RECEIVE_PORT=4991/;
                s/SEND_GROUP=.*/SEND_GROUP=$(echo $chan_num | sed s/.0/.99/)/; s/LOG_FILE=.*/LOG_FILE=ingest-test.log/;
                s/$flc/$flc-bw/" $file
}


function recv-test {
        cp $path/recv.conf.example $path/recv-test.conf
        file=$path/recv-test.conf
        sed -i "s/MOON_PORT=.*/MOON_PORT=$overlay/; s/RECEIVE_GROUP=.*/RECEIVE_GROUP=$(echo $chan_num | sed "s/.0/.99/")/;
                s/LOG_FILE=.*/LOG_FILE=recv-test.log/; s/BUF_TIME=.*/BUF_TIME=150/; s/FLOWC_ID=.*/FLOWC_ID=$(echo $flc | sed s/-i/-recv-bw/)/" $file
}


#Function invocation
typeset -f ingest | ssh -p 3999 $host "$(cat); ingest"
typeset -f ingest-test | ssh -p 3999 $host "$(cat); ingest-test"
typeset -f recv-test | ssh -p 3999 $host "$(cat); recv-test"
#cd $path
#ls

#Configure Schedule Agent
#cd ~ltn/ous/schedule_agent
#sed -i 's/ENDPOINT_NAME = TODO/ENDPOINT_NAME = $(hostname)/'
